name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - master  # Substitua pela sua branch principal, se for diferente
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 2: Configurar o Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Passo 3: Instalar dependências
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Passo 4: Construir o site com Jekyll
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          PAGES_REPO_NWO: gabriel-affonso/Obsidian.Vault.4

      # Passo 5: Fazer upload do artefato gerado para o GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
